<!-- footer.inc -->
<footer class="footer">
    <ul class="footer__list">
        <li><i class="fa-solid fa-clock"></i> Mon–Sat: 8:00 AM – 6:00 PM</li>
        <li><i class="fa-solid fa-phone"></i> +1 555 123 4567</li>
        <li><i class="fa-solid fa-location-dot"></i> 22 Ha Noi</li>
    </ul>

    <p>
        Visit our
        <a href="https://dinhphu177.atlassian.net/jira/software/projects/WTPP1/boards/34/backlog">jira project</a>
    </p>
</footer>

</body>
</html>
