<!-- header.inc -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FutureTech Solutions</title>

    <!-- FONT + ICONS -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/abf7c8298f.js" crossorigin="anonymous"></script>

    <!-- CSS -->
    <link rel="stylesheet" href="styles/style.css">
</head>
<body>
